Title: User Configuration for Western Balkan Study
Developer: Md Eliasinul Islam, Emir Fejzic
Affiliation: Sustainable Energy Engineering, Simon Fraser University, BC, Canada

version: 2.0
Release_Year: 2025
description: |+
  Inside the user configuration file of the L:INKING TOOL, there are 'keys' with quantitative 'values' upon which the module results relies on.
  These  have been given as 'parameters' in the RULES

country: 'Western Balkan Regions' # Western Balkan Regions

multi_country_flag: True # True if the 'country' represents a multi-country region   and 'regions' are nations, False if it is a single country and 'regions' are sub-nations.

default_CRS:
  degrees: EPSG:4326
  meters: EPSG:3035 # ETRS89-extended / LAEA Europe - appropriate for European analysis

# Note: All WB states are east of London. Use GMT+1 (CET) in winter, GMT+2 (CEST) in summer (last Sunday of March to last Sunday of October).
# The 'Etc/GMT-2' value in timezone_convert reflects GMT+2 (CEST). Adjust logic in code if you need to distinguish between CET and CEST.

region_mapping:

  'AL':
    name: "Albania"
    land_area_km2: 28,748
    percentage_national_land_area: "100%" # Since it's a country
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    # region_mapping: {}
    GWA_country_code: 'ALB'
    CRS_meters: EPSG:3035

  'BA':
    name: "Bosnia and Herzegovina"
    land_area_km2: 51,209
    percentage_national_land_area: "100%"
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    # region_mapping: {}
    GWA_country_code: 'BIH'
    CRS_meters: EPSG:3035

  'XK':
    name: "Kosovo"
    land_area_km2: 10,887
    percentage_national_land_area: "100%"
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    # region_mapping: {}
    GWA_country_code: 'XKX'
    CRS_meters: EPSG:3035

  'ME':
    name: "Montenegro"
    land_area_km2: 13,812
    percentage_national_land_area: "100%"
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    GWA_country_code: 'MNE'
    CRS_meters: EPSG:3035

  'MK':
    name: "North Macedonia"
    land_area_km2: 25,713
    percentage_national_land_area: "100%"
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    GWA_country_code: 'MKD'
    CRS_meters: EPSG:3035

  'RS':
    name: "Serbia"
    land_area_km2: 77,474 # The conflict between Serbia and Kosovo spills over into this data. The area of Serbia stated here (i.e. 88,361 km2) includes Kosovo (as Serbia does not recognise it as a sovereign state). Without Kosovo (which is what we are going for here), it is 77,474 km2.
    percentage_national_land_area: "100%"
    timezone_convert: 'Etc/GMT-2' # Central European Time (CET, GMT+1) / Central European Summer Time (CEST, GMT+2)
    GWA_country_code: 'SRB'
    CRS_meters: EPSG:3035

admin_boundary:
  GADM:
    root: data/downloaded_data/GADM
    processed: data/processed_data/regions
    admin_level: 1 # 0=country, 1=sub-nation, 2=sub-sub-nation
    datafield_mapping:
      'NAME_0': 'Country'
      'NAME_1': 'Municipality'
      # 'NAME_2': 'City'
      # Gov:
      # not configured for Wb6

weather:
  cutout:
    root: data/downloaded_data/cutout/
    module:
    - era5
    # - sarah

    dx: 0.25 # Arc Length for cutout grids cells in Degrees
    dy: 0.25 # Arc Length for cutout grids cells in Degrees

  GWA:
    root: 'data/downloaded_data/GWA'
    datafields: [ 'windspeed_gwa', 'CF_IEC3' ]
    sources:
      windspeed_gwa: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/wind-speed/100' # replace GWA_country_code with country code
      CF_IEC1: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC1/' #rotor dia 112m
      CF_IEC2: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC2' #rotor dia 126m
      CF_IEC3: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC3' #rotor dia 136m
      # IEC_Class_fatugue_loads: 'https://globalwindatlas.info/api/gis/country/CAN/IEC-class-fatigue-loads-incl-wake/'
      # IEC_Class_ExLoads: 'https://globalwindatlas.info/api/gis/country/CAN/IEC-class-extreme-loads/' #IEC_Class_ExtremeLoads
    rasters:
      windspeed_gwa: 'GWA_country_code_wspd_100m.tif' # replace GWA_country_code with country code
      CF_IEC1: 'GWA_country_code_capacity-factor_IEC1.tif'
      CF_IEC2: 'GWA_country_code_capacity-factor_IEC2.tif'
      CF_IEC3: 'GWA_country_code_capacity-factor_IEC3.tif'
      # IEC_Class_ExLoads: 'GWA_country_code_IEC-class-extreme-loads.tif'
    filter:
      windspeed_low: 5 # meter/s
      windspeed_high: 80 # meter/s # The extreme wind speed above which the wind turbine is not expected to operate.

technology:
  annual_technology_baseline:
    # Annual technology Baseline (ATB) - 2024\
    root: 'data/downloaded_data/NREL/ATB'
    source:
      # parquet file recommended for less memory usage
      # excel: https://data.openei.org/files/6006/2024%20v2%20Annual%20Technology%20Baseline%20Workbook%20Errata%207-19-2024.xlsx
      csv: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/csv/2024/ATBe.csv
      parquet: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/parquet/2024/v3.0.0/ATBe.parquet
    datafile:
      # excel: https://data.openei.org/files/6006/2024%20v2%20Annual%20Technology%20Baseline%20Workbook%20Errata%207-19-2024.xlsx
      csv: ATBe.csv #96 MB
      parquet: ATBe.parquet #5 MB
    about: https://atb.nrel.gov/electricity/2024/technologies
    column: 'core_metric_parameter'
    cost_params:
      # capex: 'CAPEX' # $/ kW
      capex: 'OCC' # $/ kW
      fom: 'Fixed O&M' # mill. $/ MW
      vom: 'None' # Not found for solar,wind,bess

  resource_specs:
    solar:
      max_capacity: 10 # GW
      landuse_intensity: 1.45 # (.01*145 MW/km2) ; Source: PyPSA-EUR paper,
      # capex : 1161.269 # USD/kW  ***Replaced with NREL ATB Spreadsheet (via data pipeline automation) for different wind class, different years.
      cost_data: 'data/processed_data/utility_PV_Class5_cost_moderate_NREL_ATB2024.csv'
      NREL_ATB_technology: 'UtilityPV'
      NREL_ATB_type: 'Class5' # for more : https://atb.nrel.gov/electricity/2023/utility-scale_pv
      atlite_panel: 'CSi' # CSi , CdTe
      tracking: 'dual' # None, horizontal,tilted_horizontal,vertical,dual
      cell_static_CF_tolerance: 0.16
      cell_capacity_tolerance: 1 #MW
      WCSS_tolerance: 0.08 # Within-cluster Sum of Square # Bigger number denotes bigger tolerance, hence reduced number of clusters, recommended 0.08 for solar, 0.1 for wind

    wind:
      max_capacity: 20 # GW
      landuse_intensity: 3 # (0.3 * 10 MW/km2); Source: PyPSA-EUR paper,
      # capex : 1323.4 # USD/kW  *** Replaced with NREL ATB Spreadsheet (via data pipeline automation) for different wind class, different years
      cost_data: 'data/processed_data/land_based_wind_T3_cost_moderate_NREL_ATB2024.csv'
      WCSS_tolerance: 0.1 # Within-cluster Sum of Square # Bigger number denotes bigger tolerance, hence reduced number of clusters
      CF_low: 0.20
      CF_high: 1
      NREL_ATB_technology: 'LandbasedWind'
      turbines:
        #From  existing system at BC (> 3MW turbines)
        NREL_ATB_type: 'Wind Turbine Technology 3' # Turbine Type 3 (of NREL method), size : ~ 3.3 MW, 148 m Rotor Dia, HubHeight 100m, wind plant ~ 200MW
        atlite:
          1:
            name: 'Enercon_E82_3000kW' #rotor_dia 82m
            ID: {} # N/A
            P: 3 #Nominal Power
          2:
            name: 'Vestas_V90_3MW' #rotor_dia 90m
            ID: {} # N/A
            P: 3 #Nominal Power
        OEDB:
          source: 'https://openenergy-platform.org/api/v0/schema/supply/tables/wind_turbine_library/rows'
          models:
            1:
              name: 'GE2.75_120' #rotor_dia 120m
              ID: 116
              P: 2.75 #Nominal Power
              manufacturer: 'GE Wind'
              # config: xxx
            2:
              name: '3.2M114_NES' #rotor_dia 114m
              ID: 93
              P: 3.2 #Nominal Power
              manufacturer: 'Senvion/REpower'
              config: 'data/downloaded_data/OEDB/3.2M114_NES.yaml'

infrastructure:
  OSM:
    # OpenStreet Map
    root: 'data/downloaded_data/OSM'
    data_keys:
      # has to be inline with OSM tags
      aeroway:
        tags: [ 'aerodrome', 'runway', 'taxiway', 'helipad', 'apron', 'gate' ]
      power:
        tags: [ 'line', 'cable', 'minor_line', 'substation', 'tower', 'pole', 'generator', 'plant', 'terminal' ]
      substation:
        tags: [ 'transmission', 'distribution', 'minor_distribution', 'industrial' ]
  transmission:
    grid_connection_cost_per_Km: 2.6 # M$/km   # from MISO , may try NREL method for different range of distance
    tx_line_rebuild_cost: 0.56 #M$/km # from MISO
    proximity_filter_km: 200

lands:
  default_dtype: uint8
  default_fill_value: 255

  GAEZ:
    root: 'data/downloaded_data/GAEZ'
    source: 'https://s3.eu-west-1.amazonaws.com/data.gaezdev.aws.fao.org/LR.zip'
    zip_file: 'LR.zip'
    processed_root: data/processed_data/GAEZ
    raster_types:
    # GAEZ exclusion layer
    - name: 'exclusion_areas'
      raster: "exclusion_2017.tif"
      zip_extract_direct: 'LR/excl'
      color_map: 'OrRd'
      dtype: uint8
      fill_value: 255
      stepwise_plot_title: "Excluding Global Exclusion Areas"
      class_exclusion:
        solar: [ 2, 3, 4, 5, 6, 7 ]
        wind: [ 2, 3, 4, 5, 6, 7 ]
        buffer:
          solar: 0
          wind: 0
    # GAEZ terrain slope layer
    - name: 'terrain_resources'
      raster: "slpmed05.tif"
      zip_extract_direct: 'LR/ter'
      color_map: 'terrain'
      dtype: uint8
      fill_value: 255
      stepwise_plot_title: "Excluding Terrain Slope"
      class_exclusion:
        solar: [ 8, 9 ]
        wind: [ 7, 8, 9 ]
        buffer:
          solar: 0
          wind: 0

  EU_DEM:
    root: 'data/downloaded_data/EU_DEM'
    processed: 'data/processed_data/EU_DEM'
    raster_types:
    - name: 'terrain_slope_percent_100m'
      raster: "WB6_slope_pct_100m.tif"
      color_map: 'terrain'
      dtype: float32
      fill_value: 255
      stepwise_plot_title: "Terrain Slope (%) (Copernicus DEM GLO-30, 100 m avg)"

    - name: 'terrain_slope_class'
      raster: "WB6_slope_class_uint8.tif"
      color_map: 'terrain'
      dtype: uint8
      fill_value: 255
      stepwise_plot_title: "Excluding Terrain Slope (Copernicus DEM GLO-30)"
      class_exclusion:
        solar: [ 6, 7, 8 ] # add 9 if you set a water class
        wind: [ 6, 7, 8 ]
        buffer: { solar: 0, wind: 0 }
      # 1 : no exclusion
      # 2 : IUCN category in WDPA
      # 3 : WDPA, not an IUCN category
      # 4 : KBA, outside protected areas
      # 5 : GLWD-3 class 4-9, outside protected area and KBA polygons
      # 6 : buffers around protected areas (30 arc sec buffer)
      # 7 : water


      # GAEZ v4 Median slope class compiled from 3 arc-second SRTM data

      # 1 : flat (slope angle 0-0.5%)
      # 2 : flat (slope angle 0.5-2%)
      # 3 : low slope (slope angle 2-5%)
      # 4 : low slope (slope angle 5-8%)
      # 5 : moderate slope (slope angle 8-16%)
      # 6 : moderate slope (slope angle 16-30%)
      # 7 : high slope (slope angle 30-45%)
      # 8 : high slope (slope angle >45%)
      # 9 : Water

      # - name: 'land_cover'
      #   raster: "faocmb_2010.tif" # Dominant land cover/use ; 11 classes; (5 arc-minute)
      #   zip_extract_direct: 'LR/lco'
      #   color_map: 'YlGn'
      #   stepwise_plot_title: "Excluding not-Suitable Landcovers"
      #   class_inclusion:
      #     # 1 : artificial surfaces
      #     # 2 : cropland
      #     # 3 : grassland
      #     # 4 : forest/ tree covered areas
      #     # 5 : shrubs covered areas
      #     # 6 : herbaceous vegetation,aquatic or regularly flooded areas
      #     # 7 : mangroves
      #     # 8 : sparse vegetation
      #     # 9 : bare soil
      #     # 10: snow and glaciers
      #     # 11: water bodies
      #     solar: [ 2, 3, 5, 6, 8, 9 ]
      #     wind: [ 2, 3, 5, 6, 8, 9 ]

  CORINE:
    root: 'data/downloaded_data/CORINE'
    raster_types:
    - name: 'CORINE_land_cover'
      source: 'https://copernicus-fme.eea.europa.eu/fmedatadownload/results/13521.zip'
      root: 'data/downloaded_data/CORINE'
      raster: 'U2018_CLC2018_V2020_20u1.tif'
      color_map: 'tab20'
      dtype: uint8
      fill_value: 255
      stepwise_plot_title: "Excluding not-Suitable CORINE Landcovers"
      class_inclusion:
        #solar: [7, 8, 9, 27, 28, 29, 31, 32, 38] # Old layers that were just assumed 'reasonable'
        #wind:  [7, 8, 12, 23, 18, 26, 27, 28, 29, 31, 32, 33] # Old layers that were just assumed 'reasonable'
        solar: [ 2, 3, 7, 12, 15, 18, 20, 21, 28, 32 ] # New layers based on where solar power plants are built today
        wind: [ 12, 18, 21, 23, 26, 28, 29, 32 ] # New layers based on where wind power plants are built today

demand_indicators:
  WorldPop:
    root: 'data/downloaded_data/WorldPop'
    source:
      population_density_CAN: 'https://data.worldpop.org/GIS/Population_Density/Global_2000_2020_1km_UNadj/2020/CAN/can_pd_2020_1km_UNadj_ASCII_XYZ.zip'
      population_count_CAN: 'https://data.worldpop.org/GIS/Population/Global_2000_2020_1km_UNadj/2020/CAN/can_ppp_2020_1km_UNadj_ASCII_XYZ.zip'
      weighted_population_density_EARTH: 'https://data.worldpop.org/GIS/Population_Weighted_Density/Unconstrained_Subnational/1km/PWD_1km_sub_national_geojson.zip'
      # more_data : https://www.worldpop.org/datacatalog/

filters:
  solar:
    vector_buffers:
    #list of dictionaries
    - aeroway:
        buffer_mapping_key: 'aeroway'
        buffer_mapping_key_buffers:
          # Buffer distances in meters for each aeroway type
          aerodrome: 100 # m
          runway: 100 # m
          taxiway: 100 # m
          helipad: 100 # m
          apron: 100 # m
          gate: 100 # m

  wind:
    vector_buffers:
    #list of dictionaries
    - aeroway:
        buffer_mapping_key: 'aeroway'
        buffer_mapping_key_buffers:
          # Buffer distances in meters for each aeroway type
          aerodrome: 100 # m
          runway: 100 # m
          taxiway: 100 # m
          helipad: 100 # m
          apron: 100 # m
          gate: 100 # m
