Title: User Configuration for RESource Tool
Developer : Md Eliasinul Islam (Elias Islam)
Affiliation : Sustainable Energy Engineering, Simon Fraser University, BC, Canada

version: 1.0
Release_Year: 2025
description: |+
    Inside the user configuration file of the L:INKING TOOL, there are 'keys' with quantitative 'values' upon which the module results relies on.
    These  have been given as 'parameters' in the RULES


Scenario: 
  1 :
    Name: Reference
    Description: A base scenario with reasonable assumptions.

country: Canada

region_mapping:
  'AB': 
    name: "Alberta"
    land_area_km2: 642,317
    land_area_mi2: 275,000
    percentage_national_land_area: "7.1%"
    timezone_convert: 'Etc/GMT-7' # Mountain Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

    
  'BC': 
    name: "British Columbia"
    land_area_km2: 925,186
    land_area_mi2: 357,216
    percentage_national_land_area: "10.4%"
    snapshots_tz_BC: # Hardcoded alternate measures of 'timezone_convert', supported by Pypsa
      start: 
      - '2021-01-01 00:00:00' # YYYY-MM-DD "2021-01-01 07:00:00"
      end: 
      - '2021-12-31 23:00:00' # YYYY-MM-DD "2022-01-01 06:00:00"
    timezone_convert: 'Etc/GMT+7' # Pacific Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'
    
  'MB': 
    name: "Manitoba"
    land_area_km2: 553,556
    land_area_mi2: 213,733
    percentage_national_land_area: "6.1%"
    timezone_convert: 'Etc/GMT-6' # Central Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'NB': 
    name: "New Brunswick"
    land_area_km2: 71,450
    land_area_mi2: 27,587
    percentage_national_land_area: "0.8%"
    timezone_convert: 'Etc/GMT-4' # Atlantic Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'NL': 
    name: "Newfoundland and Labrador"
    land_area_km2: 373,872
    land_area_mi2: 144,355
    percentage_national_land_area: "4.1%"
    timezone_convert: 'Etc/GMT-3.5' # Newfoundland Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'NS': 
    name: "Nova Scotia"
    land_area_km2: 53,338
    land_area_mi2: 20,594
    percentage_national_land_area: "0.6%"
    timezone_convert: 'Etc/GMT-4' # Atlantic Time Zone
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'ON': 
    name: "Ontario"
    land_area_km2: 917,741
    land_area_mi2: 354,348
    timezone_convert: 'Etc/GMT-5' # Eastern Time Zone
    percentage_national_land_area: "10.1%"
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'PE': 
    name: "Prince Edward Island"
    land_area_km2: 5,660
    land_area_mi2: 2,185
    timezone_convert: 'Etc/GMT-4' # Atlantic Time Zone
    percentage_national_land_area: "0.1%"
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'QC': 
    name: "Quebec"
    land_area_km2: 1,365,128
    land_area_mi2: 527,088
    timezone_convert: 'Etc/GMT-5' # Eastern Time Zone
    percentage_national_land_area: "15.0%"
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

  'SK': 
    name: "Saskatchewan"
    land_area_km2: 591,670
    land_area_mi2: 228,449
    timezone_convert: 'Etc/GMT-6' # Central Time Zone (no DST in most areas)
    percentage_national_land_area: "6.5%"
    sub_region_mapping: {}
    GWA_country_code: 'CAN'

GADM:
  root: data/downloaded_data/GADM
  processed: data/processed_data/regions
  datafield_mapping:
    'NAME_0': 'Country'
    'NAME_1': 'Province'
    'NAME_2': 'Region'

Gov:
  conservation_lands:
    url: https://data-donnees.az.ec.gc.ca/api/file?path=%2Fspecies%2Fprotectrestore%2Fcanadian-protected-conserved-areas-database%2FDatabases%2FProtectedConservedArea_2023.zip
    root: 'data/downloaded_data/Gov/Conservation_Lands'
    data_name: 'ProtectedConservedArea'  # Zip and the processed data will be saved with this prefix
    IUCN_CAT_mapping: # Check TABLE 10 of user manual from the source_url.
      1: 'Strict  Nature Reserve'
      2: 'Wilderness Area'
      3: 'National Park'
      4: 'Natural Monument or Feature'
      5: 'Habitat/Species Management Area'
      6: 'Protected Landscape/Seascape'
      7: 'Protected Area with Sustainable Use of Natural Resources'
      8: 'Interim Sites (unknown specifics)'
      9 : 'OECM areas'
    LOCATION_mapping: # Check TABLE 13 of user manual from the source_url.
      "Alberta": 1
      "British Columbia": 2
      "Manitoba": 3
      "New Brunswick": 4
      "Newfoundland and Labrador": 5
      "Northwest Territories": 6
      "Nova Scotia": 7
      "Nunavut": 8
      "Ontario": 9
      "Prince Edward Island": 10
      "Quebec": 11
      "Saskatchewan": 12
      "Yukon": 13
      
      # not in use
      "Coastal Arctic Marine": 14
      "Coastal Atlantic Marine": 15
      "Coastal Pacific Marine": 16
      "Offshore Arctic Marine": 17
      "Offshore Atlantic Marine": 18
      "Offshore Pacific Marine": 19
      "Arctic Marine Coastal/Offshore": 20
      "Offshore Arctic/Atlantic Marine": 21

    LAND_OWNER_mapping:
      1: "Federal Govt."
      2: "Provincial / territorial Govt"
      3: "Municipal government"
      4: "Indigenous Community/People"
      5: "Communal ownership"
      6: "Individual landowners"
      7: "For-profit organizations" # (private companies or corporations – crown corporations should be reported as federal or provincial/territory)"
      8: "Non-profit organizations"
      9: "Joint ownership" #Under the joint ownership of more than one actor, representing more than one accepted value (e.g. non-profit organizations and for-profit organizations)"
      10: "Multiple ownership" # Different parts of the land and/or waters are owned by different actors, representing more than one accepted value"
      11: "Contested Ownership" # is contested
      12: "not known or reported" # by the data provider

    data_license: https://catalogue.ec.gc.ca/geonetwork/oilsands/api/records/6c343726-1e92-451a-876a-76e17d398a1c
  Population:
    root: 'data/downloaded_data/Gov/Population'
    datafile: 'Population_Projections.csv'
    skiprows: 6 # top 6 rows are data descriptions
    different_name_mapping: # these names differs with GADM naming
      Columbia Shuswap: Columbia-Shuswap
      Strathcona: Comox-Strathcona
      Metro Vancouver: Greater Vancouver
      Metro-Vancouver : Greater Vancouver
      qathet: Powell River
      North Coast: Skeena-Queen Charlotte
      Stikine (Census Division): Stikine
      Northern Rockies (Census Division): Northern Rockies
  CEEI: #Community Energy and Emissions Inventory
    root: 'data/downloaded_data/Gov/CEEI'
    datafile:
      buildings: bc_utilities_energy_and_emissions_data_at_the_community_level.xlsx
      transportation: bc_on_road_transportation_data_at_the_community_level.xlsx
      waste: bc_municipal_solid_waste_data_at_the_community_level.xlsx
    source:
      buildings: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_utilities_energy_and_emissions_data_at_the_community_level.xlsx
      transportation: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_on_road_transportation_data_at_the_community_level.xlsx
      waste: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_municipal_solid_waste_data_at_the_community_level.xlsx

NREL: 
  ATB: # Annual technology Baseline (ATB) - 2024\
    root : 'data/downloaded_data/NREL/ATB'
    source: # parquet file recommended for less memory usage
      # excel: https://data.openei.org/files/6006/2024%20v2%20Annual%20Technology%20Baseline%20Workbook%20Errata%207-19-2024.xlsx
      csv: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/csv/2024/ATBe.csv
      parquet: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/parquet/2024/v3.0.0/ATBe.parquet
    datafile:
      # excel: https://data.openei.org/files/6006/2024%20v2%20Annual%20Technology%20Baseline%20Workbook%20Errata%207-19-2024.xlsx
      csv: ATBe.csv #96 MB
      parquet: ATBe.parquet #5 MB
    about: https://atb.nrel.gov/electricity/2024/technologies
    column: 'core_metric_parameter'
    cost_params:
      # capex: 'CAPEX' # $/ kW
      capex: 'OCC' # $/ kW
      fom: 'Fixed O&M' # mill. $/ MW
      vom: 'None' # Not found for solar,wind,bess
 
OSM_data: # OpenStreet Map
  root: 'data/downloaded_data/OSM'
  data_keys: # has to be inline with OSM tags
    aeroway:
      tags: ['aerodrome', 'runway', 'taxiway', 'helipad', 'apron', 'gate']
    power:
      tags: ['line', 'cable', 'minor_line', 'substation', 'tower', 'pole', 'generator', 'plant', 'terminal']
    substation:
      tags: ['transmission', 'distribution', 'minor_distribution', 'industrial']    

# --------------------------------------------------------------
# Canada Specific Data Source
CODERS:
  url_1: https://sesit.dev/
  url_2: http://206.12.95.102/
  api_documentation: https://sesit.dev/api/docs
  data_pull:
    root: data/downloaded_data/CODERS
    # the following mapping directs where to dump the datafile (.csvs)
    substations: network
    transmission_lines: network
  # >>>> Not required (at this dev. stage)
    # generation_generic: supply
    # hydro_existing: supply
    # generators: supply
    # hydro_cascade: supply
    # forecasted_peak_demand: demand
    # forecasted_annual_demand: demand
    # end_use_demand: demand
    # transmission_generic : network
# --------------------------------------------------------------

custom_land_layers:
  rasters:
    raster_1: # You can define any name here
      'raster': {} #Raster or path to raster which to exclude.
      'class_exclusion' : {} #Raster Classes
      'buffer': {}
      'invert': 'False' # TRUE = inclusion. FALSE = Exclusion
  vectors:
    vector_1: # You can define any name here
      'geometry': {} #Raster path
      'buffer':
      'invert': 'False'

GAEZ:
  root: 'data/downloaded_data/GAEZ'
  self.: 'https://s3.eu-west-1.amazonaws.com/data.gaezdev.aws.fao.org/LR.zip'
  zip_file: 'LR.zip'
  Rasters_in_use_direct: 'Rasters_in_use'
  raster_types:
    - name: 'land_cover'
      raster: "faocmb_2010.tif"  # Dominant land cover/use ; 11 classes; (5 arc-minute)
      zip_extract_direct: 'LR/lco'
      color_map: 'YlGn'
      class_inclusion:
        solar: [2, 3, 5, 8, 9]
        wind: [2, 3, 5, 8, 9]
        
    - name: 'terrain_resources'
      raster: "slpmed05.tif" # Median terrain slope classes; 8 classes ; (5 arc-minute)
      zip_extract_direct: 'LR/ter'
      color_map: 'terrain'
      class_exclusion:
        solar: [9]
        wind: [7, 8, 9]
        buffer:
          solar: 0 #m
          wind: 500 #m

    - name: 'exclusion_areas'
      raster: "exclusion_2017.tif" # Exclusion areas defined by Int'l orgs ; 7 classes;
      zip_extract_direct: 'LR/excl'
      color_map: 'OrRd'
      class_exclusion:
        solar: [2, 3, 4, 5, 6, 7]
        wind: [2, 3, 4, 5, 6, 7]
        buffer: 
          solar: 500 #m
          wind: 500 #m
          
WorldPop:
  root: 'data/downloaded_data/WorldPop'
  source : 
    population_density_CAN: 'https://data.worldpop.org/GIS/Population_Density/Global_2000_2020_1km_UNadj/2020/CAN/can_pd_2020_1km_UNadj_ASCII_XYZ.zip'
    population_count_CAN: 'https://data.worldpop.org/GIS/Population/Global_2000_2020_1km_UNadj/2020/CAN/can_ppp_2020_1km_UNadj_ASCII_XYZ.zip'
    weighted_population_density_EARTH: 'https://data.worldpop.org/GIS/Population_Weighted_Density/Unconstrained_Subnational/1km/PWD_1km_sub_national_geojson.zip'
    # more_data : https://www.worldpop.org/datacatalog/
        
cutout:
  root: data/downloaded_data/cutout/
  module:
    - era5
  dx: 0.25 # Arc Length for cutout grids cells in Degrees
  dy: 0.25 # Arc Length for cutout grids cells in Degrees
  
  snapshots: 
    # The start and end dates are used to filter the data for the specified time period, to synchronize with the rest of the data.
    start: # Must be formatted as 'YYYY-MM-DD' (ERA5 returns data in UTC)
      - '2023-01-01 07:00:00' # YYYY-MM-DD "2021-01-01 07:00:00"
    end:
      - '2024-01-01 06:00:00' # 6 # YYYY-MM-DD "2022-01-01 06:00:00"


GWA:
  root: 'data/downloaded_data/GWA'
  datafields: ['windspeed_gwa', 'CF_IEC2','CF_IEC3' ] #,'IEC_Class_ExLoads'
  sources:
    windspeed_gwa: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/wind-speed/100'
    # CF_IEC1: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC1/'  #rotor dia 112m
    CF_IEC2: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC2' #rotor dia 126m
    CF_IEC3: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/capacity-factor_IEC3'   #rotor dia 136m
    # IEC_Class_fatugue_loads: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/IEC-class-fatigue-loads-incl-wake/'
    IEC_Class_ExLoads: 'https://globalwindatlas.info/api/gis/country/GWA_country_code/IEC-class-extreme-loads/' #IEC_Class_ExtremeLoads
  rasters:
    windspeed_gwa: 'Canada_wspd_100m.tif'
    # CF_IEC1: 'CAN_capacity-factor_IEC1.tif'
    CF_IEC2: 'CAN_capacity-factor_IEC2.tif'
    CF_IEC3: 'CAN_capacity-factor_IEC3.tif'
    IEC_Class_ExLoads: 'CAN.IEC-class-extreme-loads.tif'
  filter:
    windspeed_low: 7 # meter/s
    windspeed_high: 40 # meter/s

capacity_disaggregation:
  solar:
    max_capacity: 5  # GW
    landuse_intensity : 1.45  # (.01*145 MW/km2) ; Source: PyPSA-EUR paper, 
    # capex : 1161.269 # USD/kW  *** Later to be linked to NREL ATB Spreadsheet (via data pipeline automation) for different wind class, different years.
    cost_data: 'data/processed_data/solar/utility_PV_Class5_cost_moderate_NREL_ATB2024.csv'
    NREL_ATB_technology: 'LandbasedWind'
    NREL_ATB_type : 'Class5' # for more : https://atb.nrel.gov/electricity/2023/utility-scale_pv
    atlite_panel: 'CSi' # CSi , CdTe
    tracking : 'dual' # None, horizontal,tilted_horizontal,vertical,dual
    cell_static_CF_tolerance: 0.16
    cell_capacity_tolerance: 1 #MW
    WCSS_tolerance: 0.005 # Within-cluster Sum of Square # Bigger number denotes bigger tolerance, hence reduced number of clusters
    buffer:
      aeroway: 100 # m
      conserved_lands: 1000 #m
    
  wind:
    max_capacity: 15  # GW
    landuse_intensity : 3  # (0.3 * 10 MW/km2); Source: PyPSA-EUR paper,
    # capex : 1323.4 # USD/kW  *** Later to be linked to NREL ATB Spreadsheet (via data pipeline automation) for different wind class, different years
    cost_data: 'data/processed_data/wind/land_based_wind_T3_cost_moderate_NREL_ATB2024.csv'
    WCSS_tolerance: 0.001 # Within-cluster Sum of Square # Bigger number denotes bigger tolerance, hence reduced number of clusters
    CF_low: 0.20
    CF_high: 1
    NREL_ATB_technology: 'LandbasedWind'
    turbines: #From  existing system at BC (> 3MW turbines)
      NREL_ATB_type : 'Wind Turbine Technology 3' # Turbine Type 3 (of NREL method), size : ~ 3.3 MW, 148 m Rotor Dia, HubHeight 100m, wind plant ~ 200MW
      atlite:
        1: 
          name: 'Enercon_E82_3000kW' #rotor_dia 82m
          ID: {} # N/A
          P: 3 #Nominal Power
        2': 
          name: 'Vestas_V90_3MW' #rotor_dia 90m
          ID: {} # N/A
          P: 3 #Nominal Power
      OEDB:
        source: 'https://openenergy-platform.org/api/v0/schema/supply/tables/wind_turbine_library/rows'
        models:
          1:
            name: 'GE2.75_120' #rotor_dia 120m
            ID: 116
            P: 2.75 #Nominal Power
            manufacturer: 'GE Wind'
            # config: xxx
          2:
            name: '3.2M114_NES' #rotor_dia 114m
            ID: 93
            P: 3.2 #Nominal Power
            manufacturer: 'Senvion/REpower'
            config: 'data/downloaded_data/OEDB/3.2M114_NES.yaml'
    buffer:
      aeroway: 1000 # m
      conserved_lands: 2000 #m
  bess:
    max_capacity : 10 #GW
    cost_data: 'data/processed_data/bess/bess_LI_6hr_cost_moderate_NREL_ATB2024.csv'
    NREL_ATB_type: '6Hr Battery Storage' # storage_discharge_duration should be in-line with this. Other options are
    vom: 0 # not found in NREL,ATB
    unit_size: 60 #MW; default in NREL is 50 MW
    residential_energy_consumption_year: 2021 # BESS cluster size calculation is associated to this year' data
    Based on general industry data and the needs of a region with a balanced energy mix like BC, you might consider the following approximate range:
    capacity_estimate_per_energy_unit:    # MW per GWh of energy consumption.
      Conservative: 0.01 
      Moderate : 0.05 
      Optimistic : 0.1 
    storage_discharge_duration : 5.5 # hr  ; the battery cost should be inline with this data.

  transmission:
    grid_connection_cost_per_Km : 2.6 #M$/km   # from MISO , may try NREL method for different range of distance
    tx_line_rebuild_cost : 0.56   #M$/km # from MISO
    proximity_filter: 100 #km
    buses: 'data/processed_data/buses_BC.csv'
    lines: 'data/processed_data/lines_BC.csv'  #future scope usage