GADM:
  data: 'Global Administrative Regions (GADM)'
  source: https://gadm.org/download_country.html
  instruction: "Select 'Country', Check for the 'GeoJSON' type data and download 'level2'"
  remarks: "Geopackage, Shapefile data works similarly. This tool has been designed to fit with GeoJSON data."
