name: RES
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core Scientific Computing
  - numpy
  - pandas
  - scipy
  - xarray
  
  # Geospatial (conda-forge has better geospatial packages)
  - geopandas
  - rasterio
  - shapely
  - fiona
  - pyproj
  - cartopy
  
  # Visualization
  - matplotlib
  - seaborn
  - plotly
  
  # Weather and Climate Data
  - netcdf4
  - h5py
  
  # Machine Learning
  - scikit-learn
  - joblib
  
  # Utilities
  - pyyaml
  - tqdm
  - click
  
  # Development
  - ipykernel
  - jupyter
  - jupyterlab
  
  # Documentation
  - sphinx
  
  # Pip-only packages (not available in conda or better from pip)
  - pip
  - pip:
    - atlite
    - cdsapi
    - pygadm
    - folium
    - dash
    - dash-bootstrap-components
    - pyrosm
    - osmnx
    - myst-parser
    - sphinx-book-theme
    - nbsphinx
    - sphinx-autobuild
    - ghp-import
    - openpyxl
    - pyarrow
    - beautifulsoup4
    - requests
    - flask
    - rioxarray
    - geojson
